### ISSUE TITLE
utserver stoping

### ISSUE THREAD

**Issue by iNili** [vortex-5/utorrent_initd#1]
I don't know if you still dev this script but i have 1000 files on seed, when i stop utserver "sudo service utorrent stop" half of 1000 files let say 500 are stoped and reported to tracker, but 500 other remain on my profile, so cannot stoping all files, those 500 remain orphaned till a later time when server detects them as orphaned and remove from my profile. 

When i stoped utserver i noticed a little delay, GOOD! if lasted a little more will stop all files on my tracker profile and in the end will make a full report 0 files to server tracker.

Ofcourse i am talking about private tracker.
Please, can you  extend the wait of stop a little more?

**Comment by vortex-5** [comment]
when you type service utorrent stop it doesn't stop the torrents it kills the server process.

Eventually the tracker will realize you area no longer seeding.

Waiting longer shouldn't help if the process is no longer running.

Also the initd script is a bit out of date my updated script is in upstart format.
